version: '2'

services:
  boot:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_boot
    command: sudo mysqld --wsrep-new-cluster
    networks:
      mariadb:
        ipv4_address: 192.168.200.10
    volumes:
      - ./boot:/etc/mysql/conf.d
      - ./sql_script:/script
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - GALERA=On
      - NODE_NAME=boot

  node1:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node1
    command: sudo bash -c "sleep 3; mysqld"
    networks:
      mariadb:
        ipv4_address: 192.168.200.11
    volumes:
    - ./node1:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node1

  node2:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node2
    command: sudo bash -c "sleep 3; mysqld"
    networks:
      mariadb:
        ipv4_address: 192.168.200.12
    volumes:
    - ./node2:/etc/mysql/conf.d
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - GALERA=On
    - NODE_NAME=node2


networks:
  mariadb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1