version: '2'

services:
  boot:
    image: lydrin/mariadb-galera-5.5
    container_name: boot
    command: mysqld --wsrep-new-cluster
    volumes:
    - ./boot:/etc/mysql/conf.d
    - ./data/mariadb/boot:/var/lib/mysql
    - ./data/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    networks:
      - bea

  node1:
    image: lydrin/mariadb-galera-5.5
    container_name: node1
    command: sudo bash -c "sleep 3; mysqld"
    volumes:
    - ./node1:/etc/mysql/conf.d
    - ./data/mariadb/node1:/var/lib/mysql
    networks:
      - bea

  node2:
    image: lydrin/mariadb-galera-5.5
    container_name: node2
    command: sudo bash -c "sleep 3; mysqld"
    volumes:
    - ./node2:/etc/mysql/conf.d
    - ./data/mariadb/node2:/var/lib/mysql
    networks:
      - bea

networks:
  bea:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.42.0/24


#  keycloak:
#    image: jboss/keycloak
#    container_name: keycloak
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./data/keycloak/apiman-realm.json:/tmp/apiman-realm.json
#    ports:
#      - 4242:8080
#    environment:
#      - DB_VENDOR=mariadb
#      - DB_ADDR=172.17.150.96:3306,172.17.150.96:3307,172.17.150.96
#      - DB_PORT=3308
#      - DB_DATABASE=keycloak
#      - DB_USER=keycloak
#      - DB_PASSWORD=keycloak
#      - KEYCLOAK_USER=keycloak
#      - KEYCLOAK_PASSWORD=keycloak
#      - PROXY_ADDRESS_FORWARDING=true
#      - KEYCLOAK_IMPORT=/tmp/apiman-realm.json
