version: '2'

services:
  boot:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_boot
    command: sudo mysqld --wsrep-new-cluster --wsrep-cluster-name=galera_cluster --wsrep-cluster-address=gcomm://
    networks:
      mariadb:
        ipv4_address: 192.168.200.10
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - GALERA=On
      - NODE_NAME=boot

  node1:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node1
    command: sudo bash -c "sleep 3; mysqld --wsrep-cluster-name=galera_cluster --wsrep-cluster-address=gcomm://192.168.200.10 --wsrep_sst_receive_address=192.168.200.11"
    networks:
      mariadb:
        ipv4_address: 192.168.200.11
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node1

  node2:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node2
    command: sudo bash -c "sleep 3; mysqld --wsrep-cluster-name=galera_cluster --wsrep-cluster-address=gcomm://192.168.200.10 --wsrep_sst_receive_address=192.168.200.12"
    networks:
      mariadb:
        ipv4_address: 192.168.200.12
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - GALERA=On
    - NODE_NAME=node1


networks:
  mariadb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1