version: '2'

services:
  boot:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_boot
    command: mysqld --wsrep-new-cluster
    ports:
      - 3306:3306
      - 4567:4567
      - 4568:4568
      - 4444:4444
    volumes:
      - ./boot:/etc/mysql/conf.d
      - ./data/mariadb/boot:/var/lib/mysql
      - ./data/mariadb/boot/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mariadb

  node1:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node1
    command: sudo bash -c "sleep 3; mysqld"
    ports:
      - 3307:3306
      - 14567:14567
      - 14568:14568
      - 4445:4445
    volumes:
      - ./node1:/etc/mysql/conf.d
      - ./data/mariadb/node1:/var/lib/mysql

  node2:
    image: lydrin/mariadb-galera-5.5
    container_name: maria_node2
    command: sudo bash -c "sleep 3; mysqld"
    ports:
      - 3308:3306
      - 24567:24567
      - 24568:24568
      - 4446:4446
    volumes:
      - ./node2:/etc/mysql/conf.d
      - ./data/mariadb/node2:/var/lib/mysql


#  keycloak:
#    image: jboss/keycloak
#    container_name: keycloak
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./data/keycloak/apiman-realm.json:/tmp/apiman-realm.json
#    ports:
#      - 4242:8080
#    environment:
#      - DB_VENDOR=mariadb
#      - DB_ADDR=172.17.150.96:3306,172.17.150.96:3307,172.17.150.96
#      - DB_PORT=3308
#      - DB_DATABASE=keycloak
#      - DB_USER=keycloak
#      - DB_PASSWORD=keycloak
#      - KEYCLOAK_USER=keycloak
#      - KEYCLOAK_PASSWORD=keycloak
#      - PROXY_ADDRESS_FORWARDING=true
#      - KEYCLOAK_IMPORT=/tmp/apiman-realm.json
